import type { LocaleCode } from './config';

export type PolicyKey = 'editorial' | 'ethics' | 'openAccess' | 'privacy' | 'terms' | 'accessibility';

export interface PolicyCopy {
  title: string;
  description: string;
  lede: string;
  sections: Record<string, string>;
  railTitle: string;
  railText: string;
  scopeLabel?: string;
  scopeText?: string;
  scopeLink?: string;
  railLabel?: string;
  railStatement?: string;
  railMeta?: string;
  railNote?: string;
}

type PolicySet = Record<PolicyKey, PolicyCopy>;

const en: PolicySet = {
  editorial: {
    title: 'Editorial Standards', description: 'Panorama Scholarly Group’s group-wide editorial standards for responsible, transparent, and rigorous scholarly publishing.', lede: 'A group-wide framework for selecting, reviewing, publishing, and maintaining trustworthy scholarly work.',
    sections: { scope: 'Purpose and scope', principles: 'Editorial principles', roles: 'Roles and responsibilities', 'peer-review': 'Peer review', integrity: 'Research integrity', transparency: 'Transparency and disclosure', record: 'The scholarly record', appeals: 'Appeals and concerns' },
    railTitle: 'The standard in practice', railText: 'Independent decisions. Transparent processes. A scholarly record that can be corrected.', scopeLabel: 'Applies across the group', scopeText: 'Journals, books, and other scholarly works published by Panorama Scholarly Group and its imprints.', scopeLink: 'Read the standard', railLabel: 'The standard in practice', railStatement: 'Independent decisions. Transparent processes. A scholarly record that can be corrected.', railMeta: 'Group-level framework', railNote: 'Individual journals and imprints may publish additional requirements for a discipline, article type, book project, or submission format.',
  },
  ethics: {
    title: 'Publication Ethics', description: 'Panorama Scholarly Group’s group-wide policy for research integrity, ethical editorial practice, and stewardship of the scholarly record.', lede: 'A group-wide framework for research integrity, fair editorial practice, and responsible stewardship of the published record.',
    sections: { purpose: 'Purpose and scope', integrity: 'Research and publication integrity', authorship: 'Authorship and contributorship', review: 'Editorial assessment and peer review', disclosure: 'Conflicts and transparency', oversight: 'Ethical oversight and participant protection', concerns: 'Concerns, complaints, and investigations', record: 'Corrections, expressions of concern, and retractions', appeals: 'Appeals and post-publication discussion', responsibility: 'Publisher responsibility and contact' },
    railTitle: 'A responsible record', railText: 'Integrity concerns are handled through documented procedures, fair process, and a commitment to keeping the published record clear.',
  },
  openAccess: {
    title: 'Open Access Policy', description: 'Panorama Scholarly Group’s policy for open access, copyright, licensing, fees, and responsible reuse of scholarly works.', lede: 'Clear access terms for authors, readers, and users of the scholarly record.',
    sections: { purpose: 'Purpose and scope', routes: 'Open-access routes', copyright: 'Copyright and publishing rights', licenses: 'License options', reuse: 'Attribution and permitted reuse', 'third-party': 'Third-party material and exclusions', data: 'Data, code, and supplementary material', fees: 'Charges, waivers, and editorial independence', record: 'Version of record and post-publication status', responsibilities: 'Responsibilities and contact' },
    railTitle: 'Open access in practice', railText: 'Open by design, licensed with precision, and reusable with confidence. The licence shown on the version of record is the authoritative reuse notice for that work.',
  },
  privacy: {
    title: 'Privacy Policy', description: 'How Panorama Scholarly Group handles information connected with the public corporate website.', lede: 'A concise account of what this website receives, why it is used, and how to raise a privacy question.',
    sections: { scope: 'Scope and responsibility', information: 'Information we receive', use: 'How information is used', sharing: 'Sharing and external services', retention: 'Retention and security', choices: 'Your choices and requests', 'changes-contact': 'Changes and contact' },
    railTitle: 'Privacy by design', railText: 'This corporate website is built to provide public information without requiring an account or collecting data for advertising.',
  },
  terms: {
    title: 'Terms of Use', description: 'Terms that govern access to and use of the Panorama Scholarly Group website.', lede: 'The conditions for using this website and the public information provided by Panorama Scholarly Group.',
    sections: { acceptance: 'Acceptance and scope', content: 'Scholarly content', 'permitted-use': 'Permitted use', rights: 'Intellectual property', external: 'External platforms', communications: 'User communications', disclaimer: 'Disclaimers and liability', 'changes-contact': 'Changes and contact' },
    railTitle: 'Use with care', railText: 'The site supports discovery and communication. Publication, submission, licensing, and research services may have additional terms of their own.',
  },
  accessibility: {
    title: 'Accessibility', description: 'Panorama Scholarly Group’s commitment to an accessible corporate website and digital publishing presence.', lede: 'We want scholarly information to be usable by as many people as possible, across devices, browsers, and assistive technologies.',
    sections: { commitment: 'Our commitment', standard: 'Standard and approach', features: 'Accessibility in practice', boundaries: 'Known boundaries', feedback: 'Feedback and assistance', updates: 'Updates and contact' },
    railTitle: 'Designed for access', railText: 'Accessibility is part of how we structure content, write interfaces, and maintain a public scholarly record.',
  },
};

const zhHans: PolicySet = {
  editorial: { ...en.editorial, title: '编辑标准', description: 'Panorama Scholarly Group 关于负责任、透明且严谨学术出版的集团级编辑标准。', lede: '适用于可信学术成果遴选、评审、出版与后续维护的集团级框架。', sections: { scope: '目的与适用范围', principles: '编辑原则', roles: '角色与责任', 'peer-review': '同行评审', integrity: '研究诚信', transparency: '透明度与披露', record: '学术记录', appeals: '申诉与问题反馈' }, railTitle: '标准如何落实', railText: '独立决策，透明流程，以及可以得到更正的学术记录。', scopeLabel: '适用于整个集团', scopeText: '适用于 Panorama Scholarly Group 及其出版品牌出版的期刊、图书与其他学术成果。', scopeLink: '阅读标准', railLabel: '标准如何落实', railStatement: '独立决策，透明流程，以及可以得到更正的学术记录。', railMeta: '集团级框架', railNote: '具体期刊和品牌可以针对学科、文章类型、图书项目或投稿形式制定补充要求。' },
  ethics: { ...en.ethics, title: '出版伦理', description: 'Panorama Scholarly Group 关于研究诚信、合乎伦理的编辑实践与学术记录维护的集团级政策。', lede: '关于研究诚信、公平编辑实践与负责任维护已出版学术记录的集团级框架。', sections: { purpose: '目的与适用范围', integrity: '研究与出版诚信', authorship: '作者署名与贡献', review: '编辑评估与同行评审', disclosure: '利益冲突与透明度', oversight: '伦理审查与参与者保护', concerns: '问题、投诉与调查', record: '更正、关注声明与撤稿', appeals: '申诉与出版后讨论', responsibility: '出版方责任与联系' }, railTitle: '负责任的学术记录', railText: '我们通过书面程序、公平流程与清晰维护已发表记录的承诺处理诚信问题。' },
  openAccess: { ...en.openAccess, title: '开放获取政策', description: 'Panorama Scholarly Group 关于开放获取、版权、许可、费用与学术成果负责任再利用的政策。', lede: '为作者、读者及学术记录使用者提供清晰的获取与再利用条件。', sections: { purpose: '目的与适用范围', routes: '开放获取路径', copyright: '版权与出版权利', licenses: '许可选项', reuse: '署名与允许的再利用', 'third-party': '第三方材料与排除项', data: '数据、代码与补充材料', fees: '费用、豁免与编辑独立性', record: '正式记录版本与出版后状态', responsibilities: '责任与联系' }, railTitle: '开放获取的实际应用', railText: '以开放为设计原则，以准确许可为基础，并让再利用更有依据。正式记录版本所载许可是该成果最权威的再利用说明。' },
  privacy: { ...en.privacy, title: '隐私政策', description: 'Panorama Scholarly Group 如何处理与集团公共网站相关的信息。', lede: '说明本网站接收哪些信息、为何使用这些信息，以及如何提出隐私问题。', sections: { scope: '适用范围与责任', information: '我们接收的信息', use: '信息的使用方式', sharing: '信息共享与外部服务', retention: '保留与安全', choices: '您的选择与请求', 'changes-contact': '变更与联系' }, railTitle: '隐私保护设计', railText: '本集团网站旨在提供公共信息，不要求用户注册账户，也不为广告目的收集数据。' },
  terms: { ...en.terms, title: '使用条款', description: '规范访问和使用 Panorama Scholarly Group 网站的条款。', lede: '使用本网站及 Panorama Scholarly Group 提供的公共信息时适用的条件。', sections: { acceptance: '接受与适用范围', content: '学术内容', 'permitted-use': '允许的使用方式', rights: '知识产权', external: '外部平台', communications: '用户通信', disclaimer: '免责声明与责任限制', 'changes-contact': '变更与联系' }, railTitle: '请审慎使用', railText: '本网站用于信息发现与沟通。出版、投稿、许可和研究服务可能另有适用条款。' },
  accessibility: { ...en.accessibility, title: '无障碍声明', description: 'Panorama Scholarly Group 对无障碍集团网站和数字出版体验的承诺。', lede: '我们希望尽可能多的人能够通过不同设备、浏览器和辅助技术使用学术信息。', sections: { commitment: '我们的承诺', standard: '标准与方法', features: '无障碍实践', boundaries: '已知边界', feedback: '反馈与协助', updates: '更新与联系' }, railTitle: '为可访问而设计', railText: '无障碍是我们组织内容、编写界面以及维护公共学术记录的重要原则。' },
};

const zhHant: PolicySet = {
  editorial: { ...zhHans.editorial, title: '編輯標準', description: 'Panorama Scholarly Group 關於負責任、透明且嚴謹學術出版的集團級編輯標準。', lede: '適用於可信學術成果遴選、評審、出版與後續維護的集團級框架。', sections: { scope: '目的與適用範圍', principles: '編輯原則', roles: '角色與責任', 'peer-review': '同行評審', integrity: '研究誠信', transparency: '透明度與披露', record: '學術記錄', appeals: '申訴與問題回饋' }, railTitle: '標準如何落實', railText: '獨立決策、透明流程，以及可以得到更正的學術記錄。', scopeLabel: '適用於整個集團', scopeText: '適用於 Panorama Scholarly Group 及其出版品牌出版的期刊、圖書與其他學術成果。', scopeLink: '閱讀標準', railLabel: '標準如何落實', railStatement: '獨立決策、透明流程，以及可以得到更正的學術記錄。', railMeta: '集團級框架', railNote: '具體期刊和品牌可以針對學科、文章類型、圖書項目或投稿形式制定補充要求' },
  ethics: { ...zhHans.ethics, title: '出版倫理', description: 'Panorama Scholarly Group 關於研究誠信、合乎倫理的編輯實踐與學術記錄維護的集團級政策。', lede: '關於研究誠信、公平編輯實踐與負責任維護已出版學術記錄的集團級框架。', sections: { purpose: '目的與適用範圍', integrity: '研究與出版誠信', authorship: '作者署名與貢獻', review: '編輯評估與同行評審', disclosure: '利益衝突與透明度', oversight: '倫理審查與參與者保護', concerns: '問題、投訴與調查', record: '更正、關注聲明與撤稿', appeals: '申訴與出版後討論', responsibility: '出版方責任與聯絡' }, railTitle: '負責任的學術記錄', railText: '我們透過書面程序、公平流程與清晰維護已發表記錄的承諾處理誠信問題。' },
  openAccess: { ...zhHans.openAccess, title: '開放取用政策', description: 'Panorama Scholarly Group 關於開放取用、版權、授權、費用與學術成果負責任再利用的政策。', lede: '為作者、讀者及學術記錄使用者提供清晰的取用與再利用條件。', sections: { purpose: '目的與適用範圍', routes: '開放取用路徑', copyright: '版權與出版權利', licenses: '授權選項', reuse: '署名與允許的再利用', 'third-party': '第三方材料與排除項', data: '資料、程式碼與補充材料', fees: '費用、豁免與編輯獨立性', record: '正式記錄版本與出版後狀態', responsibilities: '責任與聯絡' }, railTitle: '開放取用的實際應用', railText: '以開放為設計原則，以準確授權為基礎，讓再利用更有依據。正式記錄版本所載授權是該成果最權威的再利用說明。' },
  privacy: { ...zhHans.privacy, title: '私隱政策', description: 'Panorama Scholarly Group 如何處理與集團公共網站相關的資訊。', lede: '說明本網站接收哪些資訊、為何使用這些資訊，以及如何提出私隱問題。', sections: { scope: '適用範圍與責任', information: '我們接收的資訊', use: '資訊的使用方式', sharing: '資訊共享與外部服務', retention: '保留與安全', choices: '您的選擇與請求', 'changes-contact': '變更與聯絡' }, railTitle: '私隱保護設計', railText: '本集團網站旨在提供公共資訊，不要求使用者註冊帳戶，也不為廣告目的收集資料。' },
  terms: { ...zhHans.terms, title: '使用條款', description: '規範訪問和使用 Panorama Scholarly Group 網站的條款。', lede: '使用本網站及 Panorama Scholarly Group 提供的公共資訊時適用的條件。', sections: { acceptance: '接受與適用範圍', content: '學術內容', 'permitted-use': '允許的使用方式', rights: '知識產權', external: '外部平台', communications: '使用者通訊', disclaimer: '免責聲明與責任限制', 'changes-contact': '變更與聯絡' }, railTitle: '請審慎使用', railText: '本網站用於資訊發現與溝通。出版、投稿、授權和研究服務可能另有適用條款。' },
  accessibility: { ...zhHans.accessibility, title: '無障礙聲明', description: 'Panorama Scholarly Group 對無障礙集團網站和數碼出版體驗的承諾。', lede: '我們希望盡可能多的人能夠透過不同裝置、瀏覽器和輔助技術使用學術資訊。', sections: { commitment: '我們的承諾', standard: '標準與方法', features: '無障礙實踐', boundaries: '已知邊界', feedback: '回饋與協助', updates: '更新與聯絡' }, railTitle: '為可存取而設計', railText: '無障礙是我們組織內容、編寫介面以及維護公共學術記錄的重要原則。' },
};

const ja: PolicySet = {
  editorial: { ...en.editorial, title: '編集基準', description: '責任ある透明で厳密な学術出版のためのPanorama Scholarly Group共通編集基準。', lede: '信頼できる学術成果の選定、査読、出版、維持に適用するグループ共通の枠組みです。', sections: { scope: '目的と適用範囲', principles: '編集原則', roles: '役割と責任', 'peer-review': '査読', integrity: '研究公正', transparency: '透明性と開示', record: '学術記録', appeals: '異議申立てと懸念' }, railTitle: '実務における基準', railText: '独立した判断、透明なプロセス、訂正できる学術記録。', scopeLabel: 'グループ全体に適用', scopeText: 'Panorama Scholarly Groupと各インプリントが刊行する学術誌、書籍、その他の学術成果に適用します。', scopeLink: '基準を読む', railLabel: '実務における基準', railStatement: '独立した判断、透明なプロセス、訂正できる学術記録。', railMeta: 'グループ共通の枠組み', railNote: '各学術誌やインプリントは、分野、論文種別、書籍企画、投稿形式について追加要件を定めることがあります。' },
  ethics: { ...en.ethics, title: '出版倫理', description: '研究公正、倫理的な編集実践、学術記録の管理に関するPanorama Scholarly Group共通方針。', lede: '研究公正、公平な編集実践、公開記録の責任ある管理のための共通枠組みです。', sections: { purpose: '目的と適用範囲', integrity: '研究・出版の公正性', authorship: '著者資格と貢献', review: '編集評価と査読', disclosure: '利益相反と透明性', oversight: '倫理審査と参加者保護', concerns: '懸念、苦情、調査', record: '訂正、懸念表明、撤回', appeals: '異議申立てと出版後の議論', responsibility: '出版社の責任と連絡先' }, railTitle: '責任ある学術記録', railText: '文書化された手続き、公正なプロセス、明確な記録管理により公正性への懸念を扱います。' },
  openAccess: { ...en.openAccess, title: 'オープンアクセス方針', description: 'オープンアクセス、著作権、ライセンス、料金、学術成果の責任ある再利用に関する方針。', lede: '著者、読者、学術記録の利用者に向けた明確なアクセス条件です。', sections: { purpose: '目的と適用範囲', routes: 'オープンアクセスの方法', copyright: '著作権と出版権', licenses: 'ライセンスの選択肢', reuse: '表示と許可される再利用', 'third-party': '第三者素材と除外', data: 'データ、コード、補足資料', fees: '料金、免除、編集の独立性', record: '正式記録と出版後の状態', responsibilities: '責任と連絡先' }, railTitle: '実務におけるオープンアクセス', railText: '開かれた設計、明確なライセンス、確かな再利用。正式記録に示されたライセンスが最終的な再利用案内です。' },
  privacy: { ...en.privacy, title: 'プライバシーポリシー', description: 'Panorama Scholarly Groupが公開コーポレートサイトに関する情報をどのように扱うかを説明します。', lede: 'サイトが受け取る情報、その利用目的、プライバシーに関する問い合わせ方法を説明します。', sections: { scope: '適用範囲と責任', information: '受け取る情報', use: '情報の利用方法', sharing: '共有と外部サービス', retention: '保持とセキュリティ', choices: '選択と請求', 'changes-contact': '変更と連絡先' }, railTitle: '設計段階からのプライバシー', railText: '公開情報の提供にアカウントを求めず、広告目的のデータ収集を行わないよう設計しています。' },
  terms: { ...en.terms, title: '利用規約', description: 'Panorama Scholarly Groupウェブサイトへのアクセスと利用を定める条件。', lede: '本サイトとPanorama Scholarly Groupが提供する公開情報を利用するための条件です。', sections: { acceptance: '同意と適用範囲', content: '学術コンテンツ', 'permitted-use': '許可される利用', rights: '知的財産', external: '外部プラットフォーム', communications: '利用者からの連絡', disclaimer: '免責と責任', 'changes-contact': '変更と連絡先' }, railTitle: '慎重にご利用ください', railText: '本サイトは情報の発見と連絡を支援します。出版、投稿、ライセンス、研究サービスには別の条件が適用される場合があります。' },
  accessibility: { ...en.accessibility, title: 'アクセシビリティ', description: 'アクセシブルなコーポレートサイトとデジタル出版環境に対するPanorama Scholarly Groupの取り組み。', lede: 'さまざまな端末、ブラウザ、支援技術からできるだけ多くの人が学術情報を利用できることを目指します。', sections: { commitment: '私たちの取り組み', standard: '基準と方法', features: '実践におけるアクセシビリティ', boundaries: '既知の限界', feedback: 'フィードバックと支援', updates: '更新と連絡先' }, railTitle: '利用しやすさのための設計', railText: 'アクセシビリティは、コンテンツの構成、インターフェースの文章、公開学術記録の管理に関わる原則です。' },
};

const ko: PolicySet = {
  editorial: { ...en.editorial, title: '편집 기준', description: '책임 있고 투명하며 엄격한 학술 출판을 위한 Panorama Scholarly Group의 그룹 공통 편집 기준입니다.', lede: '신뢰할 수 있는 학술 저작물의 선정, 심사, 출판과 유지를 위한 그룹 공통 프레임워크입니다.', sections: { scope: '목적과 적용 범위', principles: '편집 원칙', roles: '역할과 책임', 'peer-review': '동료심사', integrity: '연구 진실성', transparency: '투명성과 공개', record: '학술 기록', appeals: '이의 제기와 우려' }, railTitle: '실천하는 기준', railText: '독립적 판단, 투명한 절차, 정정 가능한 학술 기록.', scopeLabel: '그룹 전체에 적용', scopeText: 'Panorama Scholarly Group과 각 임프린트가 출판하는 학술지, 도서 및 기타 학술 저작물에 적용됩니다.', scopeLink: '기준 읽기', railLabel: '실천하는 기준', railStatement: '독립적 판단, 투명한 절차, 정정 가능한 학술 기록.', railMeta: '그룹 공통 프레임워크', railNote: '개별 학술지와 임프린트는 분야, 논문 유형, 도서 기획 또는 제출 형식에 관한 추가 요건을 둘 수 있습니다.' },
  ethics: { ...en.ethics, title: '출판 윤리', description: '연구 진실성, 윤리적 편집 관행과 학술 기록 관리를 위한 Panorama Scholarly Group의 그룹 공통 정책입니다.', lede: '연구 진실성, 공정한 편집 관행과 공개 기록의 책임 있는 관리를 위한 그룹 공통 프레임워크입니다.', sections: { purpose: '목적과 적용 범위', integrity: '연구 및 출판 진실성', authorship: '저자 표시와 기여', review: '편집 평가와 동료심사', disclosure: '이해관계와 투명성', oversight: '윤리적 감독과 참여자 보호', concerns: '우려, 불만 및 조사', record: '정정, 우려 표명 및 철회', appeals: '이의 제기와 출판 후 논의', responsibility: '출판사의 책임과 문의' }, railTitle: '책임 있는 학술 기록', railText: '문서화된 절차와 공정한 과정, 명확한 기록 관리를 바탕으로 진실성에 관한 우려를 다룹니다.' },
  openAccess: { ...en.openAccess, title: '오픈 액세스 정책', description: '오픈 액세스, 저작권, 라이선스, 비용과 학술 저작물의 책임 있는 재사용에 관한 정책입니다.', lede: '저자, 독자와 학술 기록 이용자를 위한 명확한 접근 조건을 제시합니다.', sections: { purpose: '목적과 적용 범위', routes: '오픈 액세스 경로', copyright: '저작권과 출판 권리', licenses: '라이선스 선택지', reuse: '표시와 허용된 재사용', 'third-party': '제3자 자료와 제외 항목', data: '데이터, 코드와 보충 자료', fees: '비용, 면제와 편집 독립성', record: '공식 기록 버전과 출판 후 상태', responsibilities: '책임과 문의' }, railTitle: '실천하는 오픈 액세스', railText: '개방성을 바탕으로 설계하고, 라이선스를 정확히 표시하며, 책임 있는 재사용을 지원합니다. 공식 기록 버전의 라이선스가 최종적인 재사용 안내입니다.' },
  privacy: { ...en.privacy, title: '개인정보 보호정책', description: 'Panorama Scholarly Group이 그룹 공개 웹사이트와 관련된 정보를 처리하는 방식을 설명합니다.', lede: '웹사이트가 받는 정보, 사용 목적과 개인정보 관련 문의 방법을 간결하게 설명합니다.', sections: { scope: '범위와 책임', information: '수집하는 정보', use: '정보 이용 방법', sharing: '공유와 외부 서비스', retention: '보관과 보안', choices: '이용자의 선택과 요청', 'changes-contact': '변경과 문의' }, railTitle: '설계 단계의 개인정보 보호', railText: '이 웹사이트는 계정 없이 공개 정보를 제공하며 광고 목적의 데이터 수집을 하지 않도록 설계되었습니다.' },
  terms: { ...en.terms, title: '이용 약관', description: 'Panorama Scholarly Group 웹사이트의 접근과 이용을 규율하는 약관입니다.', lede: '이 웹사이트와 Panorama Scholarly Group이 제공하는 공개 정보를 이용할 때 적용되는 조건입니다.', sections: { acceptance: '동의와 범위', content: '학술 콘텐츠', 'permitted-use': '허용되는 이용', rights: '지식재산권', external: '외부 플랫폼', communications: '이용자 커뮤니케이션', disclaimer: '면책과 책임', 'changes-contact': '변경과 문의' }, railTitle: '신중하게 이용해 주세요', railText: '웹사이트는 정보 탐색과 소통을 지원합니다. 출판, 투고, 라이선스와 연구 서비스에는 별도의 약관이 적용될 수 있습니다.' },
  accessibility: { ...en.accessibility, title: '접근성', description: '접근 가능한 기업 웹사이트와 디지털 출판 환경을 위한 Panorama Scholarly Group의 약속입니다.', lede: '다양한 기기, 브라우저와 보조 기술에서 가능한 많은 사람이 학술 정보를 이용할 수 있도록 합니다.', sections: { commitment: '우리의 약속', standard: '기준과 접근 방식', features: '실천하는 접근성', boundaries: '알려진 한계', feedback: '피드백과 지원', updates: '업데이트와 문의' }, railTitle: '접근성을 위한 설계', railText: '접근성은 콘텐츠 구조, 인터페이스 문안과 공개 학술 기록을 관리하는 방식의 일부입니다.' },
};

const de: PolicySet = {
  editorial: { ...en.editorial, title: 'Redaktionsstandards', description: 'Die gruppenweiten Redaktionsstandards der Panorama Scholarly Group für verantwortungsvolles, transparentes und sorgfältiges wissenschaftliches Publizieren.', lede: 'Ein gemeinsamer Rahmen für die Auswahl, Begutachtung, Veröffentlichung und Pflege vertrauenswürdiger wissenschaftlicher Arbeiten.', sections: { scope: 'Zweck und Geltungsbereich', principles: 'Redaktionelle Grundsätze', roles: 'Rollen und Verantwortlichkeiten', 'peer-review': 'Peer Review', integrity: 'Forschungsintegrität', transparency: 'Transparenz und Offenlegung', record: 'Das wissenschaftliche Protokoll', appeals: 'Einsprüche und Bedenken' }, railTitle: 'Der Standard in der Praxis', railText: 'Unabhängige Entscheidungen. Transparente Verfahren. Ein korrigierbares wissenschaftliches Protokoll.', scopeLabel: 'Gruppenweit gültig', scopeText: 'Für Zeitschriften, Bücher und andere wissenschaftliche Werke der Panorama Scholarly Group und ihrer Imprints.', scopeLink: 'Standard lesen', railLabel: 'Der Standard in der Praxis', railStatement: 'Unabhängige Entscheidungen. Transparente Verfahren. Ein korrigierbares wissenschaftliches Protokoll.', railMeta: 'Gruppenweiter Rahmen', railNote: 'Einzelne Zeitschriften und Imprints können zusätzliche Anforderungen für Fachgebiet, Beitragstyp, Buchprojekt oder Einreichungsformat festlegen.' },
  ethics: { ...en.ethics, title: 'Publikationsethik', description: 'Gruppenweite Richtlinie der Panorama Scholarly Group zu Forschungsintegrität, ethischer Redaktion und Pflege des wissenschaftlichen Protokolls.', lede: 'Ein gemeinsamer Rahmen für Forschungsintegrität, faire Redaktion und verantwortungsvolle Pflege der veröffentlichten Aufzeichnungen.', sections: { purpose: 'Zweck und Geltungsbereich', integrity: 'Forschungs- und Publikationsintegrität', authorship: 'Autorschaft und Beiträge', review: 'Redaktionelle Prüfung und Peer Review', disclosure: 'Interessenkonflikte und Transparenz', oversight: 'Ethische Aufsicht und Schutz von Teilnehmenden', concerns: 'Bedenken, Beschwerden und Untersuchungen', record: 'Korrekturen, Bedenkenserklärungen und Rücknahmen', appeals: 'Einsprüche und Diskussion nach der Veröffentlichung', responsibility: 'Verantwortung des Verlags und Kontakt' }, railTitle: 'Ein verantwortliches Protokoll', railText: 'Integritätsbedenken werden mit dokumentierten Verfahren, fairem Prozess und klarer Pflege des veröffentlichten Protokolls behandelt.' },
  openAccess: { ...en.openAccess, title: 'Open-Access-Richtlinie', description: 'Richtlinie der Panorama Scholarly Group zu Open Access, Urheberrecht, Lizenzen, Gebühren und verantwortungsvoller Wiederverwendung wissenschaftlicher Werke.', lede: 'Klare Zugangsbedingungen für Autoren, Leser und Nutzer des wissenschaftlichen Protokolls.', sections: { purpose: 'Zweck und Geltungsbereich', routes: 'Open-Access-Wege', copyright: 'Urheberrecht und Publikationsrechte', licenses: 'Lizenzoptionen', reuse: 'Namensnennung und erlaubte Wiederverwendung', 'third-party': 'Material Dritter und Ausschlüsse', data: 'Daten, Code und Zusatzmaterial', fees: 'Gebühren, Erlasse und redaktionelle Unabhängigkeit', record: 'Version of Record und Status nach der Veröffentlichung', responsibilities: 'Verantwortung und Kontakt' }, railTitle: 'Open Access in der Praxis', railText: 'Offen konzipiert, präzise lizenziert und verlässlich wiederverwendbar. Die Lizenz der Version of Record ist die maßgebliche Wiederverwendungsangabe.' },
  privacy: { ...en.privacy, title: 'Datenschutzerklärung', description: 'Wie die Panorama Scholarly Group Informationen im Zusammenhang mit der öffentlichen Unternehmenswebsite verarbeitet.', lede: 'Ein kompakter Überblick darüber, welche Informationen diese Website erhält, warum sie verwendet werden und wie Sie eine Datenschutzfrage stellen können.', sections: { scope: 'Geltungsbereich und Verantwortung', information: 'Erhaltene Informationen', use: 'Verwendung von Informationen', sharing: 'Weitergabe und externe Dienste', retention: 'Aufbewahrung und Sicherheit', choices: 'Ihre Wahlmöglichkeiten und Anfragen', 'changes-contact': 'Änderungen und Kontakt' }, railTitle: 'Datenschutz durch Gestaltung', railText: 'Diese Unternehmenswebsite bietet öffentliche Informationen ohne Konto und sammelt keine Daten für Werbung.' },
  terms: { ...en.terms, title: 'Nutzungsbedingungen', description: 'Bedingungen für den Zugang zu und die Nutzung der Website der Panorama Scholarly Group.', lede: 'Die Bedingungen für die Nutzung dieser Website und der öffentlichen Informationen der Panorama Scholarly Group.', sections: { acceptance: 'Zustimmung und Geltungsbereich', content: 'Wissenschaftliche Inhalte', 'permitted-use': 'Zulässige Nutzung', rights: 'Geistiges Eigentum', external: 'Externe Plattformen', communications: 'Kommunikation der Nutzer', disclaimer: 'Haftungsausschlüsse und Haftung', 'changes-contact': 'Änderungen und Kontakt' }, railTitle: 'Mit Bedacht nutzen', railText: 'Die Website unterstützt Entdeckung und Kommunikation. Für Publikation, Einreichung, Lizenzen und Forschungsdienste können zusätzliche Bedingungen gelten.' },
  accessibility: { ...en.accessibility, title: 'Barrierefreiheit', description: 'Das Engagement der Panorama Scholarly Group für eine barrierefreie Unternehmenswebsite und digitale Publikationsumgebung.', lede: 'Wir möchten, dass möglichst viele Menschen wissenschaftliche Informationen mit unterschiedlichen Geräten, Browsern und Hilfstechnologien nutzen können.', sections: { commitment: 'Unser Engagement', standard: 'Standard und Ansatz', features: 'Barrierefreiheit in der Praxis', boundaries: 'Bekannte Grenzen', feedback: 'Feedback und Unterstützung', updates: 'Aktualisierungen und Kontakt' }, railTitle: 'Für Zugang gestaltet', railText: 'Barrierefreiheit prägt, wie wir Inhalte strukturieren, Oberflächen formulieren und ein öffentliches wissenschaftliches Protokoll pflegen.' },
};

const fr: PolicySet = {
  editorial: { ...en.editorial, title: 'Normes éditoriales', description: 'Les normes éditoriales communes de Panorama Scholarly Group pour une publication scientifique responsable, transparente et rigoureuse.', lede: 'Un cadre commun pour sélectionner, évaluer, publier et préserver des travaux scientifiques fiables.', sections: { scope: 'Objet et champ d’application', principles: 'Principes éditoriaux', roles: 'Rôles et responsabilités', 'peer-review': 'Évaluation par les pairs', integrity: 'Intégrité de la recherche', transparency: 'Transparence et déclarations', record: 'Le dossier scientifique', appeals: 'Recours et signalements' }, railTitle: 'La norme en pratique', railText: 'Décisions indépendantes. Procédures transparentes. Un dossier scientifique qui peut être corrigé.', scopeLabel: 'Applicable à tout le groupe', scopeText: 'Aux revues, livres et autres travaux scientifiques publiés par Panorama Scholarly Group et ses marques éditoriales.', scopeLink: 'Lire la norme', railLabel: 'La norme en pratique', railStatement: 'Décisions indépendantes. Procédures transparentes. Un dossier scientifique qui peut être corrigé.', railMeta: 'Cadre commun du groupe', railNote: 'Chaque revue ou marque peut publier des exigences supplémentaires selon la discipline, le type d’article, le projet de livre ou le format de soumission.' },
  ethics: { ...en.ethics, title: 'Éthique de la publication', description: 'La politique commune de Panorama Scholarly Group sur l’intégrité de la recherche, les pratiques éditoriales éthiques et la gestion du dossier scientifique.', lede: 'Un cadre commun pour l’intégrité de la recherche, une pratique éditoriale équitable et la gestion responsable du dossier publié.', sections: { purpose: 'Objet et champ d’application', integrity: 'Intégrité de la recherche et de la publication', authorship: 'Auteurs et contributions', review: 'Évaluation éditoriale et pairs', disclosure: 'Conflits et transparence', oversight: 'Supervision éthique et protection des participants', concerns: 'Signalements, plaintes et enquêtes', record: 'Corrections, expressions de préoccupation et rétractations', appeals: 'Recours et discussion après publication', responsibility: 'Responsabilité de l’éditeur et contact' }, railTitle: 'Un dossier responsable', railText: 'Les questions d’intégrité sont traitées selon des procédures documentées, une procédure équitable et un souci de clarté du dossier publié.' },
  openAccess: { ...en.openAccess, title: 'Politique d’accès ouvert', description: 'La politique de Panorama Scholarly Group sur l’accès ouvert, le droit d’auteur, les licences, les frais et la réutilisation responsable des travaux scientifiques.', lede: 'Des conditions d’accès claires pour les auteurs, les lecteurs et les utilisateurs du dossier scientifique.', sections: { purpose: 'Objet et champ d’application', routes: 'Voies d’accès ouvert', copyright: 'Droit d’auteur et droits de publication', licenses: 'Options de licence', reuse: 'Attribution et réutilisation autorisée', 'third-party': 'Matériel de tiers et exclusions', data: 'Données, code et documents complémentaires', fees: 'Frais, exonérations et indépendance éditoriale', record: 'Version de référence et statut après publication', responsibilities: 'Responsabilités et contact' }, railTitle: 'L’accès ouvert en pratique', railText: 'Ouvert par conception, licencié avec précision et réutilisable avec confiance. La licence figurant sur la version de référence fait foi.' },
  privacy: { ...en.privacy, title: 'Politique de confidentialité', description: 'La manière dont Panorama Scholarly Group traite les informations liées au site institutionnel public.', lede: 'Ce que le site reçoit, pourquoi ces informations sont utilisées et comment poser une question relative à la confidentialité.', sections: { scope: 'Champ d’application et responsabilité', information: 'Informations reçues', use: 'Utilisation des informations', sharing: 'Partage et services externes', retention: 'Conservation et sécurité', choices: 'Vos choix et demandes', 'changes-contact': 'Modifications et contact' }, railTitle: 'La confidentialité dès la conception', railText: 'Ce site institutionnel fournit des informations publiques sans compte et ne collecte pas de données à des fins publicitaires.' },
  terms: { ...en.terms, title: 'Conditions d’utilisation', description: 'Les conditions qui régissent l’accès au site de Panorama Scholarly Group et son utilisation.', lede: 'Les conditions applicables à l’utilisation de ce site et des informations publiques fournies par Panorama Scholarly Group.', sections: { acceptance: 'Acceptation et champ d’application', content: 'Contenu scientifique', 'permitted-use': 'Utilisation autorisée', rights: 'Propriété intellectuelle', external: 'Plateformes externes', communications: 'Communications des utilisateurs', disclaimer: 'Exclusions et responsabilité', 'changes-contact': 'Modifications et contact' }, railTitle: 'À utiliser avec discernement', railText: 'Le site facilite la découverte et la communication. La publication, la soumission, les licences et les services de recherche peuvent avoir leurs propres conditions.' },
  accessibility: { ...en.accessibility, title: 'Accessibilité', description: 'L’engagement de Panorama Scholarly Group en faveur d’un site institutionnel et d’un environnement éditorial numérique accessibles.', lede: 'Nous voulons que les informations scientifiques soient utilisables par le plus grand nombre, quels que soient l’appareil, le navigateur ou la technologie d’assistance.', sections: { commitment: 'Notre engagement', standard: 'Norme et approche', features: 'L’accessibilité en pratique', boundaries: 'Limites connues', feedback: 'Retour et assistance', updates: 'Mises à jour et contact' }, railTitle: 'Conçu pour être accessible', railText: 'L’accessibilité guide la structure de nos contenus, la rédaction de nos interfaces et la gestion du dossier scientifique public.' },
};

const es: PolicySet = {
  editorial: { ...en.editorial, title: 'Normas editoriales', description: 'Las normas editoriales comunes de Panorama Scholarly Group para una publicación académica responsable, transparente y rigurosa.', lede: 'Un marco común para seleccionar, evaluar, publicar y conservar trabajos académicos fiables.', sections: { scope: 'Objeto y alcance', principles: 'Principios editoriales', roles: 'Funciones y responsabilidades', 'peer-review': 'Evaluación por pares', integrity: 'Integridad de la investigación', transparency: 'Transparencia y declaraciones', record: 'El registro académico', appeals: 'Apelaciones y preocupaciones' }, railTitle: 'La norma en la práctica', railText: 'Decisiones independientes. Procesos transparentes. Un registro académico que puede corregirse.', scopeLabel: 'Aplicable a todo el grupo', scopeText: 'A las revistas, libros y demás trabajos académicos publicados por Panorama Scholarly Group y sus sellos.', scopeLink: 'Leer la norma', railLabel: 'La norma en la práctica', railStatement: 'Decisiones independientes. Procesos transparentes. Un registro académico que puede corregirse.', railMeta: 'Marco del grupo', railNote: 'Cada revista o sello puede establecer requisitos adicionales según la disciplina, el tipo de artículo, el proyecto editorial o el formato de envío.' },
  ethics: { ...en.ethics, title: 'Ética de la publicación', description: 'Política común de Panorama Scholarly Group sobre integridad de la investigación, práctica editorial ética y gestión del registro académico.', lede: 'Un marco común para la integridad de la investigación, una práctica editorial justa y la gestión responsable del registro publicado.', sections: { purpose: 'Objeto y alcance', integrity: 'Integridad de la investigación y la publicación', authorship: 'Autoría y contribuciones', review: 'Evaluación editorial y revisión por pares', disclosure: 'Conflictos y transparencia', oversight: 'Supervisión ética y protección de participantes', concerns: 'Preocupaciones, quejas e investigaciones', record: 'Correcciones, expresiones de preocupación y retractaciones', appeals: 'Apelaciones y debate posterior a la publicación', responsibility: 'Responsabilidad editorial y contacto' }, railTitle: 'Un registro responsable', railText: 'Las cuestiones de integridad se gestionan mediante procedimientos documentados, un proceso justo y un compromiso con la claridad del registro publicado.' },
  openAccess: { ...en.openAccess, title: 'Política de acceso abierto', description: 'Política de Panorama Scholarly Group sobre acceso abierto, derechos de autor, licencias, cargos y reutilización responsable de trabajos académicos.', lede: 'Condiciones de acceso claras para autores, lectores y usuarios del registro académico.', sections: { purpose: 'Objeto y alcance', routes: 'Vías de acceso abierto', copyright: 'Derechos de autor y publicación', licenses: 'Opciones de licencia', reuse: 'Atribución y reutilización permitida', 'third-party': 'Material de terceros y exclusiones', data: 'Datos, código y materiales complementarios', fees: 'Cargos, exenciones e independencia editorial', record: 'Versión de registro y estado posterior a la publicación', responsibilities: 'Responsabilidades y contacto' }, railTitle: 'El acceso abierto en la práctica', railText: 'Abierto por diseño, licenciado con precisión y reutilizable con confianza. La licencia de la versión de registro es la referencia autorizada.' },
  privacy: { ...en.privacy, title: 'Política de privacidad', description: 'Cómo trata Panorama Scholarly Group la información relacionada con el sitio web corporativo público.', lede: 'Qué recibe este sitio, por qué se utiliza y cómo plantear una consulta sobre privacidad.', sections: { scope: 'Alcance y responsabilidad', information: 'Información que recibimos', use: 'Cómo se utiliza la información', sharing: 'Compartición y servicios externos', retention: 'Conservación y seguridad', choices: 'Sus opciones y solicitudes', 'changes-contact': 'Cambios y contacto' }, railTitle: 'Privacidad desde el diseño', railText: 'Este sitio corporativo ofrece información pública sin exigir una cuenta ni recopilar datos para publicidad.' },
  terms: { ...en.terms, title: 'Condiciones de uso', description: 'Condiciones que rigen el acceso al sitio web de Panorama Scholarly Group y su uso.', lede: 'Condiciones para utilizar este sitio y la información pública proporcionada por Panorama Scholarly Group.', sections: { acceptance: 'Aceptación y alcance', content: 'Contenido académico', 'permitted-use': 'Usos permitidos', rights: 'Propiedad intelectual', external: 'Plataformas externas', communications: 'Comunicaciones de los usuarios', disclaimer: 'Exenciones y responsabilidad', 'changes-contact': 'Cambios y contacto' }, railTitle: 'Utilice el sitio con criterio', railText: 'El sitio facilita el descubrimiento y la comunicación. La publicación, el envío, las licencias y los servicios de investigación pueden tener condiciones adicionales.' },
  accessibility: { ...en.accessibility, title: 'Accesibilidad', description: 'Compromiso de Panorama Scholarly Group con un sitio corporativo y un entorno de publicación digital accesibles.', lede: 'Queremos que la información académica pueda ser utilizada por el mayor número de personas, en distintos dispositivos, navegadores y tecnologías de asistencia.', sections: { commitment: 'Nuestro compromiso', standard: 'Norma y enfoque', features: 'La accesibilidad en la práctica', boundaries: 'Límites conocidos', feedback: 'Comentarios y asistencia', updates: 'Actualizaciones y contacto' }, railTitle: 'Diseñado para el acceso', railText: 'La accesibilidad forma parte de cómo estructuramos el contenido, redactamos las interfaces y mantenemos un registro académico público.' },
};

const ru: PolicySet = {
  editorial: { ...en.editorial, title: 'Редакционные стандарты', description: 'Общие редакционные стандарты Panorama Scholarly Group для ответственной, прозрачной и строгой научной публикации.', lede: 'Общая система отбора, рецензирования, публикации и поддержания надёжных научных работ.', sections: { scope: 'Цель и область применения', principles: 'Редакционные принципы', roles: 'Роли и ответственность', 'peer-review': 'Рецензирование', integrity: 'Научная добросовестность', transparency: 'Прозрачность и раскрытие информации', record: 'Научная запись', appeals: 'Апелляции и вопросы' }, railTitle: 'Стандарт на практике', railText: 'Независимые решения. Прозрачные процедуры. Научная запись, которую можно исправить.', scopeLabel: 'Действует во всей группе', scopeText: 'Для журналов, книг и других научных работ, выпускаемых Panorama Scholarly Group и её издательскими направлениями.', scopeLink: 'Прочитать стандарт', railLabel: 'Стандарт на практике', railStatement: 'Независимые решения. Прозрачные процедуры. Научная запись, которую можно исправить.', railMeta: 'Общая система группы', railNote: 'Отдельные журналы и направления могут устанавливать дополнительные требования для дисциплины, типа статьи, книжного проекта или формата подачи.' },
  ethics: { ...en.ethics, title: 'Публикационная этика', description: 'Общая политика Panorama Scholarly Group в области научной добросовестности, этичной редакционной практики и ведения научной записи.', lede: 'Общая система обеспечения научной добросовестности, справедливой редакционной практики и ответственного ведения опубликованной записи.', sections: { purpose: 'Цель и область применения', integrity: 'Добросовестность исследования и публикации', authorship: 'Авторство и вклад', review: 'Редакционная оценка и рецензирование', disclosure: 'Конфликты и прозрачность', oversight: 'Этический надзор и защита участников', concerns: 'Вопросы, жалобы и расследования', record: 'Исправления, заявления о сомнениях и отзывы', appeals: 'Апелляции и обсуждение после публикации', responsibility: 'Ответственность издателя и контакты' }, railTitle: 'Ответственная научная запись', railText: 'Вопросы добросовестности рассматриваются по документированным процедурам, справедливому процессу и с заботой о ясности опубликованной записи.' },
  openAccess: { ...en.openAccess, title: 'Политика открытого доступа', description: 'Политика Panorama Scholarly Group в отношении открытого доступа, авторского права, лицензий, сборов и ответственного повторного использования научных работ.', lede: 'Понятные условия доступа для авторов, читателей и пользователей научной записи.', sections: { purpose: 'Цель и область применения', routes: 'Пути открытого доступа', copyright: 'Авторское право и права на публикацию', licenses: 'Варианты лицензий', reuse: 'Атрибуция и разрешённое использование', 'third-party': 'Материалы третьих лиц и исключения', data: 'Данные, код и дополнительные материалы', fees: 'Сборы, освобождения и редакционная независимость', record: 'Официальная версия и статус после публикации', responsibilities: 'Ответственность и контакты' }, railTitle: 'Открытый доступ на практике', railText: 'Открытость по замыслу, точное лицензирование и уверенное повторное использование. Лицензия официальной версии является главным уведомлением о правах.' },
  privacy: { ...en.privacy, title: 'Политика конфиденциальности', description: 'Как Panorama Scholarly Group обрабатывает информацию, связанную с публичным корпоративным сайтом.', lede: 'Какие сведения получает сайт, зачем они используются и как задать вопрос о конфиденциальности.', sections: { scope: 'Область применения и ответственность', information: 'Получаемая информация', use: 'Использование информации', sharing: 'Передача и внешние сервисы', retention: 'Хранение и безопасность', choices: 'Ваши возможности и запросы', 'changes-contact': 'Изменения и контакты' }, railTitle: 'Конфиденциальность по замыслу', railText: 'Корпоративный сайт предоставляет публичную информацию без учётной записи и не собирает данные для рекламы.' },
  terms: { ...en.terms, title: 'Условия использования', description: 'Условия доступа к сайту Panorama Scholarly Group и его использования.', lede: 'Условия использования этого сайта и публичной информации, предоставляемой Panorama Scholarly Group.', sections: { acceptance: 'Принятие и область применения', content: 'Научное содержание', 'permitted-use': 'Разрешённое использование', rights: 'Интеллектуальная собственность', external: 'Внешние платформы', communications: 'Сообщения пользователей', disclaimer: 'Отказ от гарантий и ответственность', 'changes-contact': 'Изменения и контакты' }, railTitle: 'Используйте внимательно', railText: 'Сайт поддерживает поиск информации и связь. Для публикации, подачи материалов, лицензирования и исследовательских услуг могут действовать отдельные условия.' },
  accessibility: { ...en.accessibility, title: 'Доступность', description: 'Обязательство Panorama Scholarly Group обеспечивать доступный корпоративный сайт и цифровую издательскую среду.', lede: 'Мы стремимся сделать научную информацию доступной как можно большему числу людей на разных устройствах, в браузерах и с помощью вспомогательных технологий.', sections: { commitment: 'Наше обязательство', standard: 'Стандарт и подход', features: 'Доступность на практике', boundaries: 'Известные ограничения', feedback: 'Отзывы и помощь', updates: 'Обновления и контакты' }, railTitle: 'Дизайн для доступа', railText: 'Доступность определяет структуру контента, язык интерфейсов и ведение открытой научной записи.' },
};

const ar: PolicySet = {
  editorial: { ...en.editorial, title: 'المعايير التحريرية', description: 'المعايير التحريرية العامة لمجموعة Panorama Scholarly Group من أجل نشر أكاديمي مسؤول وشفاف ودقيق.', lede: 'إطار عام لاختيار الأعمال الأكاديمية الموثوقة وتقييمها ونشرها والحفاظ عليها.', sections: { scope: 'الغرض ونطاق التطبيق', principles: 'المبادئ التحريرية', roles: 'الأدوار والمسؤوليات', 'peer-review': 'التحكيم العلمي', integrity: 'نزاهة البحث', transparency: 'الشفافية والإفصاح', record: 'السجل الأكاديمي', appeals: 'الاستئناف والمخاوف' }, railTitle: 'المعيار في التطبيق', railText: 'قرارات مستقلة. إجراءات شفافة. سجل أكاديمي يمكن تصحيحه.', scopeLabel: 'ينطبق على المجموعة بأكملها', scopeText: 'على الدوريات والكتب وسائر الأعمال الأكاديمية التي تنشرها Panorama Scholarly Group وعلاماتها التحريرية.', scopeLink: 'اقرأ المعيار', railLabel: 'المعيار في التطبيق', railStatement: 'قرارات مستقلة. إجراءات شفافة. سجل أكاديمي يمكن تصحيحه.', railMeta: 'إطار على مستوى المجموعة', railNote: 'قد تضع الدوريات والعلامات التحريرية متطلبات إضافية بحسب التخصص أو نوع المقالة أو مشروع الكتاب أو صيغة التقديم.' },
  ethics: { ...en.ethics, title: 'أخلاقيات النشر', description: 'سياسة Panorama Scholarly Group العامة بشأن نزاهة البحث والممارسات التحريرية الأخلاقية وإدارة السجل الأكاديمي.', lede: 'إطار عام لنزاهة البحث والممارسة التحريرية العادلة والإدارة المسؤولة للسجل المنشور.', sections: { purpose: 'الغرض ونطاق التطبيق', integrity: 'نزاهة البحث والنشر', authorship: 'التأليف والمساهمات', review: 'التقييم التحريري والتحكيم', disclosure: 'تعارض المصالح والشفافية', oversight: 'الإشراف الأخلاقي وحماية المشاركين', concerns: 'المخاوف والشكاوى والتحقيقات', record: 'التصحيحات وبيانات القلق والسحب', appeals: 'الاستئناف والنقاش بعد النشر', responsibility: 'مسؤولية الناشر ووسائل الاتصال' }, railTitle: 'سجل أكاديمي مسؤول', railText: 'نتعامل مع مخاوف النزاهة من خلال إجراءات موثقة وعملية عادلة والالتزام بوضوح السجل المنشور.' },
  openAccess: { ...en.openAccess, title: 'سياسة الوصول المفتوح', description: 'سياسة Panorama Scholarly Group بشأن الوصول المفتوح وحقوق الطبع والتراخيص والرسوم وإعادة الاستخدام المسؤولة للأعمال الأكاديمية.', lede: 'شروط وصول واضحة للمؤلفين والقراء ومستخدمي السجل الأكاديمي.', sections: { purpose: 'الغرض ونطاق التطبيق', routes: 'مسارات الوصول المفتوح', copyright: 'حقوق الطبع وحقوق النشر', licenses: 'خيارات الترخيص', reuse: 'النسبة وإعادة الاستخدام المسموح', 'third-party': 'مواد الغير والاستثناءات', data: 'البيانات والشفرة والمواد الإضافية', fees: 'الرسوم والإعفاء والاستقلال التحريري', record: 'النسخة الرسمية وحالة ما بعد النشر', responsibilities: 'المسؤوليات والاتصال' }, railTitle: 'الوصول المفتوح عمليًا', railText: 'الوصول المفتوح في التصميم، والترخيص الدقيق، وإعادة الاستخدام بثقة. ويُعد الترخيص الظاهر على النسخة الرسمية الإشعار المعتمد بحقوق الاستخدام.' },
  privacy: { ...en.privacy, title: 'سياسة الخصوصية', description: 'كيفية تعامل Panorama Scholarly Group مع المعلومات المرتبطة بالموقع المؤسسي العام.', lede: 'ما الذي يتلقاه الموقع، ولماذا يُستخدم، وكيفية طرح سؤال يتعلق بالخصوصية.', sections: { scope: 'النطاق والمسؤولية', information: 'المعلومات التي نتلقاها', use: 'كيفية استخدام المعلومات', sharing: 'المشاركة والخدمات الخارجية', retention: 'الاحتفاظ والأمان', choices: 'خياراتك وطلباتك', 'changes-contact': 'التغييرات والاتصال' }, railTitle: 'الخصوصية في التصميم', railText: 'يوفر الموقع المؤسسي معلومات عامة من دون طلب حساب أو جمع بيانات لأغراض إعلانية.' },
  terms: { ...en.terms, title: 'شروط الاستخدام', description: 'الشروط التي تنظم الوصول إلى موقع Panorama Scholarly Group واستخدامه.', lede: 'شروط استخدام هذا الموقع والمعلومات العامة التي توفرها Panorama Scholarly Group.', sections: { acceptance: 'القبول والنطاق', content: 'المحتوى الأكاديمي', 'permitted-use': 'الاستخدام المسموح', rights: 'الملكية الفكرية', external: 'المنصات الخارجية', communications: 'مراسلات المستخدمين', disclaimer: 'إخلاء المسؤولية والمسؤولية القانونية', 'changes-contact': 'التغييرات والاتصال' }, railTitle: 'استخدم الموقع بعناية', railText: 'يدعم الموقع اكتشاف المعلومات والتواصل. وقد تخضع خدمات النشر والتقديم والترخيص والبحث لشروط إضافية.' },
  accessibility: { ...en.accessibility, title: 'إمكانية الوصول', description: 'التزام Panorama Scholarly Group بإتاحة الموقع المؤسسي وبيئة النشر الرقمية.', lede: 'نريد أن تكون المعلومات الأكاديمية قابلة للاستخدام لأكبر عدد ممكن من الناس عبر الأجهزة والمتصفحات وتقنيات المساعدة المختلفة.', sections: { commitment: 'التزامنا', standard: 'المعيار والمنهج', features: 'إمكانية الوصول عمليًا', boundaries: 'الحدود المعروفة', feedback: 'الملاحظات والمساعدة', updates: 'التحديثات والاتصال' }, railTitle: 'مصمم للوصول', railText: 'تدخل إمكانية الوصول في طريقة تنظيم المحتوى وصياغة الواجهات والحفاظ على سجل أكاديمي عام.' },
};

const copy: Record<LocaleCode, PolicySet> = { en, 'zh-hans': zhHans, 'zh-hant': zhHant, ja, ko, de, fr, es, ru, ar };

export function getPolicyCopy(policy: PolicyKey, locale = 'en'): PolicyCopy {
  return copy[locale as LocaleCode]?.[policy] ?? copy.en[policy];
}
