import type { LocaleCode } from './config';

export interface PublishingRouteCopy {
  title: string;
  description: string;
  label: string;
}

export interface PublishingPageCopy {
  title: string;
  metaDescription: string;
  overline: string;
  heroTitle: string;
  heroLede: string;
  exploreJournals: string;
  meetImprints: string;
  visualAria: string;
  visualLineOne: string;
  visualLineTwo: string;
  pathwaysOverline: string;
  pathwaysTitle: string;
  routes: PublishingRouteCopy[];
  imprintsOverline: string;
  imprintsTitle: string;
  imprintsLede: string;
  activeJournals: string;
  tableAria: string;
  imprintHeader: string;
  scopeHeader: string;
  programmeHeader: string;
  activeJournalsLabel: string;
  imprintsClosing: string;
  exploreAllImprints: string;
  nextOverline: string;
  nextTitle: string;
  nextBody: string;
  editorialStandards: string;
  contactGroup: string;
}

export interface BookFormatCopy {
  name: string;
  description: string;
}

export interface BooksPageCopy {
  title: string;
  metaDescription: string;
  overline: string;
  heroTitle: string;
  heroLede: string;
  heroAlt: string;
  browseBooks: string;
  submitProposal: string;
  actionsAria: string;
  pathsTitle: string;
  readersTitle: string;
  readersBody: string;
  visitPlatform: string;
  authorsTitle: string;
  authorsBody: string;
  programmeOverline: string;
  programmeTitle: string;
  programmeIntro: string;
  formats: BookFormatCopy[];
  ctaTitle: string;
  exploreBooks: string;
}

const publishing: Record<LocaleCode, PublishingPageCopy> = {
  en: {
    title: 'Publishing',
    metaDescription: 'Explore the journals, books, imprints, and publishing standards of Panorama Scholarly Group.',
    overline: 'The publishing programme',
    heroTitle: 'Advancing scholarship through distinct editorial worlds.',
    heroLede: 'Across journals, books, and imprints, we create clear editorial homes for rigorous work and the questions that matter now.',
    exploreJournals: 'Explore journals', meetImprints: 'Meet the imprints',
    visualAria: 'Five editorial identities connected through one publishing programme', visualLineOne: 'Five imprint identities.', visualLineTwo: 'One editorial standard.',
    pathwaysOverline: 'How the programme is organised', pathwaysTitle: 'One group. Several ways into scholarship.',
    routes: [
      { title: 'Journals', description: 'Peer-reviewed journals across five editorial imprints, with a direct route to each journal website.', label: 'Explore journals' },
      { title: 'Books', description: 'Scholarly monographs and edited volumes developed through the Panorama Scholarly Books programme.', label: 'Explore books' },
      { title: 'Standards', description: 'Editorial, ethics, open-access, and accessibility principles for responsible publication.', label: 'Read standards' },
    ],
    imprintsOverline: 'Our five imprints', imprintsTitle: 'Distinctive identities. Shared standards.', imprintsLede: 'Five editorial worlds, united by a commitment to open, accountable scholarship.',
    activeJournals: 'active journals', tableAria: 'Panorama Scholarly Group imprints', imprintHeader: 'Imprint', scopeHeader: 'Scope', programmeHeader: 'Programme', activeJournalsLabel: 'Active journals',
    imprintsClosing: 'Each imprint gives a distinct editorial home to research with a shared commitment to quality and access.', exploreAllImprints: 'Explore all imprints',
    nextOverline: 'Authors. Editors. Partners.', nextTitle: 'Move scholarship forward, together.', nextBody: 'We work with researchers, editors, institutions, and scholarly communities to develop, publish, and share research with clarity, rigor, and global reach.', editorialStandards: 'Read editorial standards', contactGroup: 'Contact the group',
  },
  'zh-hans': {
    title: '出版', metaDescription: '探索 Panorama Scholarly Group 的期刊、图书、出版品牌与出版标准。', overline: '出版项目', heroTitle: '通过各具特色的编辑世界推动学术发展。', heroLede: '我们以期刊、图书与出版品牌为载体，为严谨研究及其所回应的当代问题建立清晰而持久的编辑空间。', exploreJournals: '探索期刊', meetImprints: '认识出版品牌', visualAria: '五个出版品牌通过同一出版项目相互连接', visualLineOne: '五个出版品牌。', visualLineTwo: '一套共同的编辑标准。', pathwaysOverline: '出版体系', pathwaysTitle: '一个集团，通往学术的多种路径。',
    routes: [{ title: '期刊', description: '五个出版品牌下的同行评审期刊，并直接链接至各期刊网站。', label: '探索期刊' }, { title: '图书', description: '通过 Panorama Scholarly Books 项目策划出版的学术专著与编著。', label: '探索图书' }, { title: '标准', description: '面向负责任出版的编辑、伦理、开放获取与无障碍原则。', label: '阅读出版标准' }],
    imprintsOverline: '我们的五个出版品牌', imprintsTitle: '各具特色的身份，共享出版标准。', imprintsLede: '五个编辑世界，以开放、负责的学术承诺相连。', activeJournals: '本活跃期刊', tableAria: 'Panorama Scholarly Group 出版品牌', imprintHeader: '出版品牌', scopeHeader: '范围', programmeHeader: '项目', activeJournalsLabel: '本活跃期刊', imprintsClosing: '每个品牌都为研究提供独特的编辑归属，同时遵循对质量与开放性的共同承诺。', exploreAllImprints: '探索全部出版品牌', nextOverline: '作者、编辑与合作伙伴', nextTitle: '携手推动学术发展。', nextBody: '我们与研究者、编辑、机构及学术共同体合作，以清晰、严谨并具全球影响力的方式发展、出版和传播研究成果。', editorialStandards: '阅读编辑标准', contactGroup: '联系集团',
  },
  'zh-hant': {
    title: '出版', metaDescription: '探索 Panorama Scholarly Group 的期刊、圖書、出版品牌與出版標準。', overline: '出版項目', heroTitle: '透過各具特色的編輯世界推動學術發展。', heroLede: '我們以期刊、圖書與出版品牌為載體，為嚴謹研究及其所回應的當代問題建立清晰而持久的編輯空間。', exploreJournals: '探索期刊', meetImprints: '認識出版品牌', visualAria: '五個出版品牌透過同一出版項目相互連結', visualLineOne: '五個出版品牌。', visualLineTwo: '一套共同的編輯標準。', pathwaysOverline: '出版體系', pathwaysTitle: '一個集團，通往學術的多種路徑。',
    routes: [{ title: '期刊', description: '五個出版品牌旗下的同行評審期刊，並直接連結至各期刊網站。', label: '探索期刊' }, { title: '圖書', description: '透過 Panorama Scholarly Books 項目策劃出版的學術專著與編著。', label: '探索圖書' }, { title: '標準', description: '面向負責任出版的編輯、倫理、開放取用與無障礙原則。', label: '閱讀出版標準' }],
    imprintsOverline: '我們的五個出版品牌', imprintsTitle: '各具特色的身份，共享出版標準。', imprintsLede: '五個編輯世界，以開放、負責任的學術承諾相連。', activeJournals: '本活躍期刊', tableAria: 'Panorama Scholarly Group 出版品牌', imprintHeader: '出版品牌', scopeHeader: '範圍', programmeHeader: '項目', activeJournalsLabel: '本活躍期刊', imprintsClosing: '每個品牌都為研究提供獨特的編輯歸屬，同時遵循對質量與開放性的共同承諾。', exploreAllImprints: '探索全部出版品牌', nextOverline: '作者、編輯與合作夥伴', nextTitle: '攜手推動學術發展。', nextBody: '我們與研究者、編輯、機構及學術共同體合作，以清晰、嚴謹並具全球影響力的方式發展、出版和傳播研究成果。', editorialStandards: '閱讀編輯標準', contactGroup: '聯絡集團',
  },
  ja: {
    title: '出版', metaDescription: 'Panorama Scholarly Group の学術誌、書籍、出版ブランド、出版基準をご覧ください。', overline: '出版プログラム', heroTitle: '独自の編集世界を通じて、学術を前へ。', heroLede: '学術誌、書籍、出版ブランドを通じて、厳密な研究と現代の重要な問いにふさわしい編集の場を築きます。', exploreJournals: '学術誌を見る', meetImprints: '出版ブランドを見る', visualAria: '一つの出版プログラムで結ばれた5つの編集ブランド', visualLineOne: '5つの出版ブランド。', visualLineTwo: '1つの編集基準。', pathwaysOverline: '出版プログラムの構成', pathwaysTitle: '1つのグループ。学術へ至る複数の道。',
    routes: [{ title: '学術誌', description: '5つの編集ブランドで展開する査読誌。各誌のウェブサイトへ直接アクセスできます。', label: '学術誌を見る' }, { title: '書籍', description: 'Panorama Scholarly Books が刊行する学術モノグラフと論文集。', label: '書籍を見る' }, { title: '基準', description: '責任ある出版のための編集、倫理、オープンアクセス、アクセシビリティの原則。', label: '基準を読む' }],
    imprintsOverline: '5つの出版ブランド', imprintsTitle: '異なる個性。共有する基準。', imprintsLede: '5つの編集世界を、開かれた責任ある学術への約束で結びます。', activeJournals: '誌の学術誌', tableAria: 'Panorama Scholarly Group の出版ブランド', imprintHeader: 'ブランド', scopeHeader: '領域', programmeHeader: 'プログラム', activeJournalsLabel: '誌の学術誌', imprintsClosing: '各ブランドは、質とアクセスへの共通の約束のもと、研究に固有の編集の場を提供します。', exploreAllImprints: 'すべての出版ブランドを見る', nextOverline: '著者。編集者。パートナー。', nextTitle: 'ともに学術を前へ進める。', nextBody: '研究者、編集者、機関、学術コミュニティと協力し、明確さ、厳密さ、世界への広がりを備えた研究を育て、刊行し、共有します。', editorialStandards: '編集基準を読む', contactGroup: 'グループに連絡する',
  },
  ko: {
    title: '출판', metaDescription: 'Panorama Scholarly Group의 저널, 도서, 출판 브랜드와 출판 기준을 살펴보세요.', overline: '출판 프로그램', heroTitle: '서로 다른 편집 세계를 통해 학술을 발전시킵니다.', heroLede: '저널, 도서, 출판 브랜드를 통해 엄밀한 연구와 오늘날의 중요한 질문을 담아낼 분명한 편집의 장을 만듭니다.', exploreJournals: '저널 둘러보기', meetImprints: '출판 브랜드 보기', visualAria: '하나의 출판 프로그램으로 연결된 다섯 출판 브랜드', visualLineOne: '다섯 출판 브랜드.', visualLineTwo: '하나의 편집 기준.', pathwaysOverline: '출판 프로그램의 구성', pathwaysTitle: '하나의 그룹. 학술로 향하는 여러 경로.',
    routes: [{ title: '저널', description: '다섯 편집 브랜드에서 발행하는 동료심사 저널과 각 저널 웹사이트로의 직접 경로를 제공합니다.', label: '저널 둘러보기' }, { title: '도서', description: 'Panorama Scholarly Books 프로그램을 통해 개발하는 학술 단행본과 편저입니다.', label: '도서 둘러보기' }, { title: '기준', description: '책임 있는 출판을 위한 편집, 윤리, 오픈 액세스, 접근성 원칙입니다.', label: '기준 읽기' }],
    imprintsOverline: '다섯 출판 브랜드', imprintsTitle: '서로 다른 정체성. 공유하는 기준.', imprintsLede: '다섯 편집 세계를 개방적이고 책임 있는 학술에 대한 약속으로 연결합니다.', activeJournals: '개 저널', tableAria: 'Panorama Scholarly Group 출판 브랜드', imprintHeader: '브랜드', scopeHeader: '범위', programmeHeader: '프로그램', activeJournalsLabel: '개 저널', imprintsClosing: '각 브랜드는 품질과 접근성에 대한 공동의 약속 아래 연구에 고유한 편집의 장을 제공합니다.', exploreAllImprints: '모든 출판 브랜드 보기', nextOverline: '저자. 편집자. 파트너.', nextTitle: '함께 학술을 발전시킵니다.', nextBody: '연구자, 편집자, 기관, 학술 공동체와 협력해 명확성, 엄밀성, 세계적 도달력을 갖춘 연구를 개발하고 출판하며 공유합니다.', editorialStandards: '편집 기준 읽기', contactGroup: '그룹에 문의하기',
  },
  de: {
    title: 'Publizieren', metaDescription: 'Entdecken Sie die Zeitschriften, Bücher, Verlagsmarken und Publikationsstandards der Panorama Scholarly Group.', overline: 'Das Publikationsprogramm', heroTitle: 'Wissenschaft voranbringen – durch eigenständige redaktionelle Welten.', heroLede: 'Mit Zeitschriften, Büchern und Verlagsmarken schaffen wir eigenständige redaktionelle Räume für strenge Forschung und die Fragen, die heute zählen.', exploreJournals: 'Zeitschriften entdecken', meetImprints: 'Verlagsmarken kennenlernen', visualAria: 'Fünf redaktionelle Identitäten, verbunden durch ein Publikationsprogramm', visualLineOne: 'Fünf Verlagsmarken.', visualLineTwo: 'Ein redaktioneller Standard.', pathwaysOverline: 'Aufbau des Publikationsprogramms', pathwaysTitle: 'Eine Gruppe. Mehrere Wege zur Wissenschaft.',
    routes: [{ title: 'Zeitschriften', description: 'Begutachtete Zeitschriften aus fünf Verlagsmarken – mit direktem Zugang zu jeder Zeitschriftenwebsite.', label: 'Zeitschriften entdecken' }, { title: 'Bücher', description: 'Wissenschaftliche Monografien und Sammelbände aus dem Programm Panorama Scholarly Books.', label: 'Bücher entdecken' }, { title: 'Standards', description: 'Redaktionelle, ethische, Open-Access- und Barrierefreiheitsgrundsätze für verantwortungsvolles Publizieren.', label: 'Standards lesen' }],
    imprintsOverline: 'Unsere fünf Verlagsmarken', imprintsTitle: 'Eigenständige Identitäten. Gemeinsame Standards.', imprintsLede: 'Fünf redaktionelle Welten, verbunden durch unser Bekenntnis zu offener, verantwortungsvoller Wissenschaft.', activeJournals: 'aktive Zeitschriften', tableAria: 'Verlagsmarken der Panorama Scholarly Group', imprintHeader: 'Verlagsmarke', scopeHeader: 'Profil', programmeHeader: 'Programm', activeJournalsLabel: 'Aktive Zeitschriften', imprintsClosing: 'Jede Marke gibt Forschung ein eigenständiges redaktionelles Zuhause – mit einem gemeinsamen Anspruch an Qualität und Zugang.', exploreAllImprints: 'Alle Verlagsmarken entdecken', nextOverline: 'Autoren. Herausgeber. Partner.', nextTitle: 'Gemeinsam Wissenschaft voranbringen.', nextBody: 'Wir arbeiten mit Forschenden, Herausgebern, Institutionen und wissenschaftlichen Gemeinschaften, um Forschung klar, sorgfältig und mit globaler Reichweite zu entwickeln, zu veröffentlichen und zu teilen.', editorialStandards: 'Redaktionsstandards lesen', contactGroup: 'Gruppe kontaktieren',
  },
  fr: {
    title: 'Édition', metaDescription: 'Découvrez les revues, les livres, les labels éditoriaux et les normes de publication de Panorama Scholarly Group.', overline: 'Le programme éditorial', heroTitle: 'Faire progresser les savoirs par des univers éditoriaux distincts.', heroLede: 'À travers nos revues, nos livres et nos labels, nous créons des espaces éditoriaux clairs pour des recherches rigoureuses et les questions qui comptent aujourd’hui.', exploreJournals: 'Découvrir les revues', meetImprints: 'Découvrir les labels', visualAria: 'Cinq identités éditoriales réunies par un même programme éditorial', visualLineOne: 'Cinq labels éditoriaux.', visualLineTwo: 'Une norme éditoriale commune.', pathwaysOverline: 'Organisation du programme éditorial', pathwaysTitle: 'Un groupe. Plusieurs voies vers les savoirs.',
    routes: [{ title: 'Revues', description: 'Des revues évaluées par les pairs au sein de cinq labels éditoriaux, avec un accès direct à chaque site.', label: 'Découvrir les revues' }, { title: 'Livres', description: 'Des monographies et ouvrages collectifs développés dans le programme Panorama Scholarly Books.', label: 'Découvrir les livres' }, { title: 'Normes', description: 'Des principes éditoriaux, éthiques, d’accès ouvert et d’accessibilité pour une publication responsable.', label: 'Lire les normes' }],
    imprintsOverline: 'Nos cinq labels éditoriaux', imprintsTitle: 'Des identités singulières. Des normes partagées.', imprintsLede: 'Cinq univers éditoriaux réunis par un engagement en faveur d’une recherche ouverte et responsable.', activeJournals: 'revues actives', tableAria: 'Labels éditoriaux de Panorama Scholarly Group', imprintHeader: 'Label', scopeHeader: 'Champ', programmeHeader: 'Programme', activeJournalsLabel: 'Revues actives', imprintsClosing: 'Chaque label offre un cadre éditorial distinct aux recherches, dans le respect d’un engagement commun en faveur de la qualité et de l’accès.', exploreAllImprints: 'Voir tous les labels éditoriaux', nextOverline: 'Auteurs. Éditeurs. Partenaires.', nextTitle: 'Faire progresser les savoirs, ensemble.', nextBody: 'Nous travaillons avec des chercheurs, des éditeurs, des institutions et des communautés savantes pour développer, publier et partager des recherches avec clarté, rigueur et portée internationale.', editorialStandards: 'Lire les normes éditoriales', contactGroup: 'Contacter le groupe',
  },
  es: {
    title: 'Publicación', metaDescription: 'Descubra las revistas, los libros, los sellos editoriales y las normas de publicación de Panorama Scholarly Group.', overline: 'El programa editorial', heroTitle: 'Impulsar el conocimiento a través de mundos editoriales distintos.', heroLede: 'A través de revistas, libros y sellos editoriales, creamos espacios editoriales definidos para investigaciones rigurosas y las preguntas que importan hoy.', exploreJournals: 'Explorar las revistas', meetImprints: 'Conocer los sellos', visualAria: 'Cinco identidades editoriales conectadas por un mismo programa de publicación', visualLineOne: 'Cinco sellos editoriales.', visualLineTwo: 'Una norma editorial.', pathwaysOverline: 'Estructura del programa editorial', pathwaysTitle: 'Un grupo. Varias vías hacia el conocimiento.',
    routes: [{ title: 'Revistas', description: 'Revistas revisadas por pares de cinco sellos editoriales, con acceso directo al sitio de cada revista.', label: 'Explorar las revistas' }, { title: 'Libros', description: 'Monografías académicas y obras colectivas desarrolladas mediante el programa Panorama Scholarly Books.', label: 'Explorar los libros' }, { title: 'Normas', description: 'Principios editoriales, éticos, de acceso abierto y accesibilidad para una publicación responsable.', label: 'Leer las normas' }],
    imprintsOverline: 'Nuestros cinco sellos editoriales', imprintsTitle: 'Identidades propias. Normas compartidas.', imprintsLede: 'Cinco mundos editoriales unidos por el compromiso con una investigación abierta y responsable.', activeJournals: 'revistas activas', tableAria: 'Sellos editoriales de Panorama Scholarly Group', imprintHeader: 'Sello', scopeHeader: 'Ámbito', programmeHeader: 'Programa', activeJournalsLabel: 'Revistas activas', imprintsClosing: 'Cada sello ofrece un hogar editorial propio a la investigación, con un compromiso común con la calidad y el acceso.', exploreAllImprints: 'Explorar todos los sellos', nextOverline: 'Autores. Editores. Colaboradores.', nextTitle: 'Impulsar el conocimiento, juntos.', nextBody: 'Trabajamos con investigadores, editores, instituciones y comunidades académicas para desarrollar, publicar y compartir investigaciones con claridad, rigor y alcance internacional.', editorialStandards: 'Leer las normas editoriales', contactGroup: 'Contactar con el grupo',
  },
  ru: {
    title: 'Издательская деятельность', metaDescription: 'Изучите журналы, книги, издательские направления и стандарты публикации Panorama Scholarly Group.', overline: 'Издательская программа', heroTitle: 'Развиваем науку через самостоятельные редакционные миры.', heroLede: 'В журналах, книгах и издательских направлениях мы создаём ясные редакционные пространства для строгих исследований и вопросов, важных сегодня.', exploreJournals: 'Изучить журналы', meetImprints: 'Познакомиться с направлениями', visualAria: 'Пять редакционных идентичностей, объединённых одной издательской программой', visualLineOne: 'Пять издательских направлений.', visualLineTwo: 'Единый редакционный стандарт.', pathwaysOverline: 'Устройство издательской программы', pathwaysTitle: 'Одна группа. Несколько путей к знаниям.',
    routes: [{ title: 'Журналы', description: 'Рецензируемые журналы пяти издательских направлений с прямым переходом на сайт каждого журнала.', label: 'Изучить журналы' }, { title: 'Книги', description: 'Научные монографии и сборники, подготовленные в рамках программы Panorama Scholarly Books.', label: 'Изучить книги' }, { title: 'Стандарты', description: 'Редакционные, этические, связанные с открытым доступом и доступностью принципы ответственной публикации.', label: 'Прочитать стандарты' }],
    imprintsOverline: 'Наши пять издательских направлений', imprintsTitle: 'Самостоятельные идентичности. Общие стандарты.', imprintsLede: 'Пять редакционных миров, объединённых приверженностью открытой и ответственной науке.', activeJournals: 'активных журналов', tableAria: 'Издательские направления Panorama Scholarly Group', imprintHeader: 'Направление', scopeHeader: 'Профиль', programmeHeader: 'Программа', activeJournalsLabel: 'Активные журналы', imprintsClosing: 'Каждое направление даёт исследованиям собственное редакционное пространство при общем внимании к качеству и доступу.', exploreAllImprints: 'Изучить все направления', nextOverline: 'Авторы. Редакторы. Партнёры.', nextTitle: 'Развиваем науку вместе.', nextBody: 'Мы работаем с исследователями, редакторами, учреждениями и научными сообществами, чтобы создавать, публиковать и распространять исследования ясно, строго и с глобальным охватом.', editorialStandards: 'Прочитать редакционные стандарты', contactGroup: 'Связаться с группой',
  },
  ar: {
    title: 'النشر', metaDescription: 'استكشف الدوريات والكتب والعلامات التحريرية ومعايير النشر لدى Panorama Scholarly Group.', overline: 'برنامج النشر', heroTitle: 'النهوض بالمعرفة عبر عوالم تحريرية متميزة.', heroLede: 'من خلال الدوريات والكتب والعلامات التحريرية، ننشئ أطرًا تحريرية واضحة للبحوث الرصينة والأسئلة التي تهم عالم اليوم.', exploreJournals: 'استكشف الدوريات', meetImprints: 'تعرّف إلى العلامات التحريرية', visualAria: 'هويات تحريرية خمس يجمعها برنامج نشر واحد', visualLineOne: 'خمس علامات تحريرية.', visualLineTwo: 'معيار تحريري واحد.', pathwaysOverline: 'بنية برنامج النشر', pathwaysTitle: 'مجموعة واحدة. مسارات متعددة إلى المعرفة.',
    routes: [{ title: 'الدوريات', description: 'دوريات محكّمة ضمن خمس علامات تحريرية، مع وصول مباشر إلى موقع كل دورية.', label: 'استكشف الدوريات' }, { title: 'الكتب', description: 'دراسات أحادية ومجلدات محررة تُطوَّر ضمن برنامج Panorama Scholarly Books.', label: 'استكشف الكتب' }, { title: 'المعايير', description: 'مبادئ تحريرية وأخلاقية ومبادئ للوصول المفتوح وإمكانية الوصول من أجل نشر مسؤول.', label: 'اقرأ المعايير' }],
    imprintsOverline: 'علاماتنا التحريرية الخمس', imprintsTitle: 'هويات متميزة. معايير مشتركة.', imprintsLede: 'عوالم تحريرية خمسة يجمعها الالتزام بالمعرفة المفتوحة والمسؤولة.', activeJournals: 'دورية نشطة', tableAria: 'علامات Panorama Scholarly Group التحريرية', imprintHeader: 'العلامة', scopeHeader: 'النطاق', programmeHeader: 'البرنامج', activeJournalsLabel: 'دوريات نشطة', imprintsClosing: 'تمنح كل علامة البحثَ موطنًا تحريريًا متميزًا، مع التزام مشترك بالجودة وإتاحة الوصول.', exploreAllImprints: 'استكشف جميع العلامات التحريرية', nextOverline: 'المؤلفون. المحررون. الشركاء.', nextTitle: 'ننهض بالمعرفة معًا.', nextBody: 'نعمل مع الباحثين والمحررين والمؤسسات والمجتمعات العلمية لتطوير الأبحاث ونشرها ومشاركتها بوضوح ورصانة ووصول عالمي.', editorialStandards: 'اقرأ المعايير التحريرية', contactGroup: 'تواصل مع المجموعة',
  },
};

const books: Record<LocaleCode, BooksPageCopy> = {
  en: {
    title: 'Books', metaDescription: 'Panorama Scholarly Books develops rigorous scholarship into books for readers, teachers, and researchers.', overline: 'Panorama Scholarly Books', heroTitle: 'Research becomes a lasting book.', heroLede: 'We develop rigorous scholarship into books for readers, teachers, and researchers — across disciplines and around the world.', heroAlt: "A realistic hardcover presentation of Panorama Scholarly Books' first publication, with a dark blue book behind it", browseBooks: 'Browse published books', submitProposal: 'Submit a book proposal', actionsAria: 'Book programme actions', pathsTitle: 'Explore books and publish with us', readersTitle: 'For readers', readersBody: 'Explore scholarly books from across the humanities, social sciences, education, arts, public policy, and AI and future society. Our books support research, teaching, and informed public debate.', visitPlatform: 'Visit our book platform', authorsTitle: 'For authors and editors', authorsBody: 'We welcome proposals for scholarly monographs, edited volumes, research reports, and academic textbooks. Our publishing programme supports strong ideas from proposal to publication, with a focus on academic quality, global reach, and long-term impact.', programmeOverline: 'Our publishing programme', programmeTitle: 'A home for scholarship across forms.', programmeIntro: 'Different questions call for different kinds of books. Our programme gives each work the form its scholarship needs.', formats: [{ name: 'Monographs', description: 'In-depth research on significant questions and new ideas.' }, { name: 'Edited volumes', description: 'Bringing together diverse perspectives on key topics.' }, { name: 'Research reports', description: 'Evidence and analysis for policy, practice, and society.' }, { name: 'Academic textbooks', description: 'Trusted resources for teaching and learning.' }, { name: 'Interdisciplinary works', description: 'Connecting disciplines to address complex challenges.' }], ctaTitle: 'Ideas travel further together.', exploreBooks: 'Explore our books',
  },
  'zh-hans': {
    title: '图书', metaDescription: 'Panorama Scholarly Books 将严谨学术成果发展为服务读者、教师与研究者的图书。', overline: 'Panorama Scholarly Books', heroTitle: '让研究成为持久的图书。', heroLede: '我们将严谨学术成果发展为面向全球、跨越多学科的图书，服务读者、教师与研究者。', heroAlt: 'Panorama Scholarly Books 首部出版物的精装书展示，后方衬有深蓝色书籍', browseBooks: '浏览已出版图书', submitProposal: '提交图书提案', actionsAria: '图书项目操作', pathsTitle: '探索图书，与我们一起出版', readersTitle: '面向读者', readersBody: '探索涵盖人文学科、社会科学、教育、艺术、公共政策以及人工智能与未来社会的学术图书。我们的图书服务于研究、教学与基于充分信息的公共讨论。', visitPlatform: '访问图书平台', authorsTitle: '面向作者与编者', authorsBody: '我们欢迎学术专著、编著、研究报告与学术教材提案。出版项目从提案到出版支持有价值的学术思想，重视学术质量、全球传播与长期影响。', programmeOverline: '我们的出版项目', programmeTitle: '让不同形式都成为学术的归宿。', programmeIntro: '不同问题需要不同类型的图书。我们的项目为每项研究提供与其学术内容相称的形式。', formats: [{ name: '学术专著', description: '围绕重要问题与新思想展开的深入研究。' }, { name: '编著', description: '汇集围绕关键主题的多元视角。' }, { name: '研究报告', description: '为政策、实践与社会提供证据与分析。' }, { name: '学术教材', description: '值得信赖的教学与学习资源。' }, { name: '跨学科著作', description: '连接不同学科，应对复杂挑战。' }], ctaTitle: '思想在共同探索中走得更远。', exploreBooks: '探索图书',
  },
  'zh-hant': {
    title: '圖書', metaDescription: 'Panorama Scholarly Books 將嚴謹學術成果發展為服務讀者、教師與研究者的圖書。', overline: 'Panorama Scholarly Books', heroTitle: '讓研究成為持久的圖書。', heroLede: '我們將嚴謹學術成果發展為面向全球、跨越多學科的圖書，服務讀者、教師與研究者。', heroAlt: 'Panorama Scholarly Books 首部出版物的精裝書展示，後方襯有深藍色書籍', browseBooks: '瀏覽已出版圖書', submitProposal: '提交圖書提案', actionsAria: '圖書項目操作', pathsTitle: '探索圖書，與我們一起出版', readersTitle: '面向讀者', readersBody: '探索涵蓋人文學科、社會科學、教育、藝術、公共政策以及人工智能與未來社會的學術圖書。我們的圖書服務於研究、教學與以充分資訊為基礎的公共討論。', visitPlatform: '訪問圖書平台', authorsTitle: '面向作者與編者', authorsBody: '我們歡迎學術專著、編著、研究報告與學術教材提案。出版項目從提案到出版支持有價值的學術思想，重視學術質量、全球傳播與長期影響。', programmeOverline: '我們的出版項目', programmeTitle: '讓不同形式都成為學術的歸宿。', programmeIntro: '不同問題需要不同類型的圖書。我們的項目為每項研究提供與其學術內容相稱的形式。', formats: [{ name: '學術專著', description: '圍繞重要問題與新思想展開的深入研究。' }, { name: '編著', description: '匯集圍繞關鍵主題的多元視角。' }, { name: '研究報告', description: '為政策、實踐與社會提供證據與分析。' }, { name: '學術教材', description: '值得信賴的教學與學習資源。' }, { name: '跨學科著作', description: '連接不同學科，應對複雜挑戰。' }], ctaTitle: '思想在共同探索中走得更遠。', exploreBooks: '探索圖書',
  },
  ja: {
    title: '書籍', metaDescription: 'Panorama Scholarly Books は、読者、教育者、研究者のために厳密な研究を書籍として刊行します。', overline: 'Panorama Scholarly Books', heroTitle: '研究を、長く残る一冊へ。', heroLede: '分野と地域を越え、読者、教育者、研究者のために厳密な学術研究を本にします。', heroAlt: 'Panorama Scholarly Books の初刊本を示すリアルなハードカバー。その背後に濃紺の本がある', browseBooks: '刊行書籍を見る', submitProposal: '書籍企画を提出', actionsAria: '書籍プログラムの操作', pathsTitle: '本を探し、私たちと出版する', readersTitle: '読者の方へ', readersBody: '人文学、社会科学、教育、芸術、公共政策、AIと未来社会にわたる学術書をご覧ください。研究、教育、十分な情報に基づく公共的議論を支えます。', visitPlatform: '書籍プラットフォームを見る', authorsTitle: '著者・編者の方へ', authorsBody: '学術モノグラフ、論文集、研究報告書、学術教科書の企画を歓迎します。学術的な質、国際的な広がり、長期的な影響を重視し、企画から刊行まで支援します。', programmeOverline: '出版プログラム', programmeTitle: '多様な形式のための学術の場。', programmeIntro: '問いが異なれば、必要な本の形も異なります。研究にふさわしい形式を提供します。', formats: [{ name: 'モノグラフ', description: '重要な問いと新しい着想を掘り下げる研究。' }, { name: '論文集', description: '主要なテーマに関する多様な視点を集めます。' }, { name: '研究報告書', description: '政策、実践、社会のための証拠と分析。' }, { name: '学術教科書', description: '教育と学習を支える信頼できる資料。' }, { name: '学際的著作', description: '分野をつなぎ、複雑な課題に取り組みます。' }], ctaTitle: '思想はともに進むことで、さらに遠くへ届く。', exploreBooks: '書籍を見る',
  },
  ko: {
    title: '도서', metaDescription: 'Panorama Scholarly Books는 독자, 교사, 연구자를 위한 엄밀한 학술 연구를 도서로 발전시킵니다.', overline: 'Panorama Scholarly Books', heroTitle: '연구를 오래 남는 책으로 만듭니다.', heroLede: '분야와 지역을 넘어 독자, 교사, 연구자를 위한 엄밀한 학술 연구를 책으로 발전시킵니다.', heroAlt: 'Panorama Scholarly Books의 첫 출판물을 보여주는 사실적인 양장본 이미지와 뒤쪽의 짙은 파란색 책', browseBooks: '출간 도서 둘러보기', submitProposal: '도서 제안서 제출', actionsAria: '도서 프로그램 작업', pathsTitle: '도서를 탐색하고 함께 출판하세요', readersTitle: '독자를 위해', readersBody: '인문학, 사회과학, 교육, 예술, 공공정책, AI와 미래 사회를 아우르는 학술 도서를 살펴보세요. 연구와 교육, 충분한 정보에 기반한 공적 논의를 지원합니다.', visitPlatform: '도서 플랫폼 방문', authorsTitle: '저자와 편집자를 위해', authorsBody: '학술 단행본, 편저, 연구 보고서, 학술 교재 제안서를 환영합니다. 학술적 품질, 세계적 도달력, 장기적 영향에 중점을 두고 기획부터 출간까지 지원합니다.', programmeOverline: '출판 프로그램', programmeTitle: '다양한 형식의 학술을 위한 자리.', programmeIntro: '질문이 다르면 필요한 책의 형태도 달라집니다. 연구에 맞는 형식을 제공합니다.', formats: [{ name: '학술 단행본', description: '중요한 질문과 새로운 아이디어를 깊이 있게 다루는 연구입니다.' }, { name: '편저', description: '핵심 주제에 대한 다양한 관점을 모읍니다.' }, { name: '연구 보고서', description: '정책, 실천, 사회를 위한 증거와 분석입니다.' }, { name: '학술 교재', description: '교육과 학습을 위한 신뢰할 수 있는 자료입니다.' }, { name: '학제 간 저술', description: '분야를 연결해 복잡한 과제에 답합니다.' }], ctaTitle: '아이디어는 함께할 때 더 멀리 나아갑니다.', exploreBooks: '도서 살펴보기',
  },
  de: {
    title: 'Bücher', metaDescription: 'Panorama Scholarly Books entwickelt anspruchsvolle Forschung zu Büchern für Leser, Lehrende und Forschende.', overline: 'Panorama Scholarly Books', heroTitle: 'Aus Forschung wird ein bleibendes Buch.', heroLede: 'Wir entwickeln anspruchsvolle Wissenschaft über Disziplinen und Regionen hinweg zu Büchern für Leser, Lehrende und Forschende.', heroAlt: 'Realistische Darstellung der ersten Publikation von Panorama Scholarly Books als Hardcover, dahinter ein dunkelblaues Buch', browseBooks: 'Veröffentlichte Bücher entdecken', submitProposal: 'Buchprojekt einreichen', actionsAria: 'Aktionen zum Buchprogramm', pathsTitle: 'Bücher entdecken und mit uns publizieren', readersTitle: 'Für Leserinnen und Leser', readersBody: 'Entdecken Sie wissenschaftliche Bücher aus Geistes- und Sozialwissenschaften, Bildung, Kunst, Public Policy sowie KI und Zukunftsgesellschaft. Unsere Bücher unterstützen Forschung, Lehre und informierte öffentliche Debatten.', visitPlatform: 'Unsere Buchplattform besuchen', authorsTitle: 'Für Autoren und Herausgeber', authorsBody: 'Wir begrüßen Vorschläge für Monografien, Sammelbände, Forschungsberichte und wissenschaftliche Lehrbücher. Unser Programm begleitet tragfähige Ideen von der Einreichung bis zur Veröffentlichung und legt Wert auf Qualität, Reichweite und langfristige Wirkung.', programmeOverline: 'Unser Publikationsprogramm', programmeTitle: 'Ein Zuhause für Wissenschaft in vielen Formen.', programmeIntro: 'Unterschiedliche Fragen verlangen unterschiedliche Bücher. Unser Programm gibt jedem Werk die Form, die seine Forschung braucht.', formats: [{ name: 'Monografien', description: 'Vertiefte Forschung zu wichtigen Fragen und neuen Ideen.' }, { name: 'Sammelbände', description: 'Vielfältige Perspektiven zu zentralen Themen.' }, { name: 'Forschungsberichte', description: 'Evidenz und Analyse für Politik, Praxis und Gesellschaft.' }, { name: 'Wissenschaftliche Lehrbücher', description: 'Verlässliche Ressourcen für Lehre und Lernen.' }, { name: 'Interdisziplinäre Werke', description: 'Disziplinen verbinden, um komplexe Herausforderungen zu bearbeiten.' }], ctaTitle: 'Gemeinsam kommen Ideen weiter.', exploreBooks: 'Unsere Bücher entdecken',
  },
  fr: {
    title: 'Livres', metaDescription: 'Panorama Scholarly Books transforme des recherches rigoureuses en livres destinés aux lecteurs, aux enseignants et aux chercheurs.', overline: 'Panorama Scholarly Books', heroTitle: 'La recherche devient un livre qui dure.', heroLede: 'Nous transformons des travaux rigoureux en livres pour les lecteurs, les enseignants et les chercheurs, dans toutes les disciplines et partout dans le monde.', heroAlt: 'Présentation réaliste en couverture rigide de la première publication de Panorama Scholarly Books, avec un livre bleu foncé en arrière-plan', browseBooks: 'Parcourir les livres publiés', submitProposal: 'Soumettre un projet de livre', actionsAria: 'Actions du programme de livres', pathsTitle: 'Découvrir nos livres et publier avec nous', readersTitle: 'Pour les lecteurs', readersBody: 'Découvrez des livres scientifiques en sciences humaines et sociales, en éducation, en arts, en politiques publiques, ainsi que sur l’IA et les sociétés futures. Ils soutiennent la recherche, l’enseignement et le débat public éclairé.', visitPlatform: 'Visiter notre plateforme de livres', authorsTitle: 'Pour les auteurs et les directeurs d’ouvrage', authorsBody: 'Nous accueillons les projets de monographies, d’ouvrages collectifs, de rapports de recherche et de manuels universitaires. Notre programme accompagne les idées solides de la proposition à la publication, en privilégiant la qualité scientifique, la portée internationale et l’impact à long terme.', programmeOverline: 'Notre programme éditorial', programmeTitle: 'Un lieu pour les savoirs sous toutes leurs formes.', programmeIntro: 'À question différente, livre différent. Notre programme donne à chaque travail la forme que sa recherche exige.', formats: [{ name: 'Monographies', description: 'Des recherches approfondies sur des questions importantes et des idées nouvelles.' }, { name: 'Ouvrages collectifs', description: 'Des perspectives diverses réunies autour de thèmes essentiels.' }, { name: 'Rapports de recherche', description: 'Des données et des analyses pour les politiques publiques, les pratiques et la société.' }, { name: 'Manuels universitaires', description: 'Des ressources fiables pour l’enseignement et l’apprentissage.' }, { name: 'Ouvrages interdisciplinaires', description: 'Relier les disciplines pour répondre à des défis complexes.' }], ctaTitle: 'Ensemble, les idées vont plus loin.', exploreBooks: 'Découvrir nos livres',
  },
  es: {
    title: 'Libros', metaDescription: 'Panorama Scholarly Books convierte investigaciones rigurosas en libros para lectores, docentes e investigadores.', overline: 'Panorama Scholarly Books', heroTitle: 'La investigación se convierte en un libro duradero.', heroLede: 'Convertimos investigaciones rigurosas en libros para lectores, docentes e investigadores, en distintas disciplinas y en todo el mundo.', heroAlt: 'Presentación realista en tapa dura de la primera publicación de Panorama Scholarly Books, con un libro azul oscuro detrás', browseBooks: 'Explorar los libros publicados', submitProposal: 'Enviar una propuesta de libro', actionsAria: 'Acciones del programa de libros', pathsTitle: 'Explore nuestros libros y publique con nosotros', readersTitle: 'Para lectores', readersBody: 'Explore libros académicos de humanidades, ciencias sociales, educación, artes, políticas públicas, IA y sociedad futura. Nuestros libros apoyan la investigación, la enseñanza y el debate público informado.', visitPlatform: 'Visitar nuestra plataforma de libros', authorsTitle: 'Para autores y editores', authorsBody: 'Aceptamos propuestas de monografías académicas, obras colectivas, informes de investigación y manuales universitarios. Nuestro programa acompaña las buenas ideas desde la propuesta hasta la publicación, con atención a la calidad académica, el alcance internacional y el impacto a largo plazo.', programmeOverline: 'Nuestro programa editorial', programmeTitle: 'Un espacio para el conocimiento en todas sus formas.', programmeIntro: 'Preguntas distintas requieren libros distintos. Nuestro programa da a cada obra la forma que necesita su investigación.', formats: [{ name: 'Monografías', description: 'Investigación profunda sobre preguntas relevantes e ideas nuevas.' }, { name: 'Obras colectivas', description: 'Perspectivas diversas reunidas en torno a temas clave.' }, { name: 'Informes de investigación', description: 'Evidencia y análisis para las políticas, la práctica y la sociedad.' }, { name: 'Manuales académicos', description: 'Recursos fiables para la enseñanza y el aprendizaje.' }, { name: 'Obras interdisciplinarias', description: 'Conectar disciplinas para abordar desafíos complejos.' }], ctaTitle: 'Juntas, las ideas llegan más lejos.', exploreBooks: 'Explorar nuestros libros',
  },
  ru: {
    title: 'Книги', metaDescription: 'Panorama Scholarly Books превращает строгие исследования в книги для читателей, преподавателей и исследователей.', overline: 'Panorama Scholarly Books', heroTitle: 'Исследование становится книгой, которая остаётся.', heroLede: 'Мы превращаем строгие исследования в книги для читателей, преподавателей и исследователей, объединяя дисциплины и страны.', heroAlt: 'Реалистичная презентация первого издания Panorama Scholarly Books в твёрдой обложке; на заднем плане — тёмно-синяя книга', browseBooks: 'Изучить опубликованные книги', submitProposal: 'Предложить книгу', actionsAria: 'Действия программы книг', pathsTitle: 'Изучайте книги и публикуйтесь вместе с нами', readersTitle: 'Для читателей', readersBody: 'Изучите научные книги по гуманитарным и социальным наукам, образованию, искусству, государственной политике, ИИ и будущему общества. Наши книги поддерживают исследования, обучение и информированную общественную дискуссию.', visitPlatform: 'Перейти на книжную платформу', authorsTitle: 'Для авторов и редакторов', authorsBody: 'Мы принимаем предложения научных монографий, сборников, исследовательских отчётов и учебников. Программа сопровождает сильные идеи от предложения до публикации, уделяя внимание научному качеству, глобальному охвату и долгосрочному воздействию.', programmeOverline: 'Наша издательская программа', programmeTitle: 'Место для знаний в разных формах.', programmeIntro: 'Разные вопросы требуют разных книг. Мы подбираем каждому труду форму, соответствующую его исследованию.', formats: [{ name: 'Монографии', description: 'Глубокие исследования важных вопросов и новых идей.' }, { name: 'Сборники', description: 'Разные перспективы по ключевым темам в одном издании.' }, { name: 'Исследовательские отчёты', description: 'Доказательства и анализ для политики, практики и общества.' }, { name: 'Учебники', description: 'Надёжные ресурсы для преподавания и обучения.' }, { name: 'Междисциплинарные работы', description: 'Связывают дисциплины для решения сложных задач.' }], ctaTitle: 'Вместе идеи достигают большего.', exploreBooks: 'Изучить наши книги',
  },
  ar: {
    title: 'الكتب', metaDescription: 'يحوّل Panorama Scholarly Books البحوث الرصينة إلى كتب للقراء والمعلمين والباحثين.', overline: 'Panorama Scholarly Books', heroTitle: 'يصبح البحث كتابًا باقياً.', heroLede: 'نطوّر المعرفة الرصينة إلى كتب للقراء والمعلمين والباحثين عبر التخصصات وفي أنحاء العالم.', heroAlt: 'عرض واقعي لغلاف أول منشورات Panorama Scholarly Books، مع كتاب أزرق داكن في الخلفية', browseBooks: 'تصفّح الكتب المنشورة', submitProposal: 'قدّم مقترح كتاب', actionsAria: 'إجراءات برنامج الكتب', pathsTitle: 'استكشف الكتب وانشر معنا', readersTitle: 'للقراء', readersBody: 'استكشف كتبًا علمية في العلوم الإنسانية والاجتماعية والتعليم والفنون والسياسات العامة والذكاء الاصطناعي ومجتمع المستقبل. تدعم كتبنا البحث والتعليم والنقاش العام المستنير.', visitPlatform: 'زيارة منصة الكتب', authorsTitle: 'للمؤلفين والمحررين', authorsBody: 'نرحب بمقترحات الدراسات الأحادية والمجلدات المحررة والتقارير البحثية والكتب الأكاديمية. يدعم برنامجنا الأفكار القوية من المقترح إلى النشر، مع التركيز على الجودة الأكاديمية والوصول العالمي والأثر طويل الأمد.', programmeOverline: 'برنامج النشر لدينا', programmeTitle: 'موطن للمعرفة بمختلف أشكالها.', programmeIntro: 'تتطلب الأسئلة المختلفة أنواعًا مختلفة من الكتب. نمنح كل عمل الشكل الذي يحتاجه بحثه.', formats: [{ name: 'دراسات أحادية', description: 'بحث متعمق في أسئلة مهمة وأفكار جديدة.' }, { name: 'مجلدات محررة', description: 'جمع وجهات نظر متنوعة حول موضوعات محورية.' }, { name: 'تقارير بحثية', description: 'أدلة وتحليل للسياسات والممارسة والمجتمع.' }, { name: 'كتب أكاديمية', description: 'موارد موثوقة للتدريس والتعلّم.' }, { name: 'أعمال متعددة التخصصات', description: 'ربط التخصصات لمعالجة التحديات المعقدة.' }], ctaTitle: 'تصل الأفكار معًا إلى مدى أبعد.', exploreBooks: 'استكشف كتبنا',
  },
};

export function getPublishingCopy(locale = 'en'): PublishingPageCopy {
  return publishing[locale as LocaleCode] ?? publishing.en;
}

export function getBooksCopy(locale = 'en'): BooksPageCopy {
  return books[locale as LocaleCode] ?? books.en;
}
